version: '3'
services:
  postgres:
    image: 'postgres:13.3-alpine'
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - /path/to/local/dir/pg_data:/var/lib/postgresql/data
    command: "-c timezone=America/Argentina/Buenos_Aires -c log_timezone=America/Argentina/Buenos_Aires"
