# Generated by Django 3.2.3 on 2021-05-17 13:04
from django.db import migrations

from scv_api.models import Team


def load_teams(apps, schema_editor):
    default_teams = ['River Plate', 'Banfield', 'Lanús', 'Defensa y Justicia', 'Newells Old Boys', 'Plantense',
                     'Patronato', 'Arsenal', 'Unión', 'Rosario', 'Talleres', 'Atl. Tucumán', 'Estudiantes',
                     'Argentinos Juniors', 'Racing Club', 'Independiente', 'Sarmiento', 'Gimnasia de La Plata', 'Colón',
                     'Córdoba SdE', 'Boca Juniors', 'Vélez', 'Aldosivi', 'Godoy Cruz', 'Huracán', 'San Lorenzo']
    for t in default_teams:
        a = Team(name=t)
        a.save()

class Migration(migrations.Migration):
    dependencies = [
        ('scv_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_teams),
    ]
